[build.environment]
  RUBY_VERSION = "3.2.2"

[build]
  command = "export RUBY_VERSION=3.2.2 && bundle install && bundle exec rake assets:precompile"
  publish = "public"

[[plugins]]
  package = "netlify-plugin-apt"

  [plugins.inputs]
  packages = [
    "libpq-dev"
  ]
