[build]
  command = "apt-get update && apt-get install -y libpq-dev && bundle exec rake assets:precompile"
  publish = "public"

[[plugins]]
  package = "netlify-plugin-apt"

  [plugins.inputs]
  packages = [
    "libpq-dev"
  ]
