[build]
  command = "export RUBY_VERSION=3.2.2 && bundle config build.pg --with-pg-config=/usr/pgsql-12/bin/pg_config && bundle install && bundle exec rake assets:precompile"
  publish = "public"

[[plugins]]
  package = "netlify-plugin-apt"

  [plugins.inputs]
  packages = [
    "libpq-dev"
  ]
