# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql  # Specify the adapter for PostgreSQL
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>  # Number of database connections in the pool
  timeout: 5000  # Connection timeout in milliseconds

development:
  <<: *default  # Inherit default settings
  url: <%= ENV['DATABASE_URL'] %>  # Use DATABASE_URL env variable (make sure it's set)
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  adapter: sqlite3  # Use SQLite for testing (unless you're using PostgreSQL for tests too)
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  url: <%= ENV['DATABASE_URL'] %>
  port: <%= ENV['DB_PORT'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
